spring:
  application:
    name: footballteam
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # JDBC ???? ?? ??
    url: jdbc:mysql://localhost:3306/chatworld?serverTimezone=Asia/Seoul  # DB ?? ?? ??
    username: namix  # DB ?? ??
    password: wjdehd123!  # DB ???? ??